version: "3.8"
services:
  slackbot:
    build:
      dockerfile: ./build/Dockerfile.local
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./configs:/app/configs
      - ./secrets:/app/secrets
    command: npm run start slackbot
    depends_on:
      - postgres
      - redis
      - base
    environment:
      NODE_OVERRIDE_ENV: local
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
# Monolith API
  base:
    image: 221762091942.dkr.ecr.us-east-1.amazonaws.com/base:stg
    environment:
      NODE_ENV: local
      PORT: 3001
    ports:
      - 3001:3001

# Databases
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
