version: "3.8"
secrets:
  aws_creds:
    file: ~/.aws

services:
  openai-proxy:
    image: 221762091942.dkr.ecr.us-east-1.amazonaws.com/openai-proxy:latest
    container_name: openai-proxy
    ports:
      - 8080:8080
    environment:
      ENV: local
      PORT: :8080
    depends_on: 
      - redis
    secrets:
      - source: aws_creds
        target: /root/.aws
    command: [  "./chamber", "exec", "openai-proxy/local", "--", "./openai-proxy" ]
  slacker:
    build:
      dockerfile: ./build/Dockerfile.local
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./configs:/app/configs
    depends_on:
      - postgres
      - redis
      - sqs
    environment:
      NODE_OVERRIDE_ENV: local${LOCAL_ENV}
      PORT: 3000
    secrets:
      - source: aws_creds
        target: /root/.aws
    command: [  "./chamber", "exec", "basebot/local${LOCAL_ENV}", "--", "npm", "run", "start", "slacker" ]
    ports:
      - 3000:3000
      - 9229:9229

  gistbot:
    build:
      dockerfile: ./build/Dockerfile.local
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./configs:/app/configs
    depends_on:
      - postgres
      - redis
      - sqs
    environment:
      NODE_OVERRIDE_ENV: local${LOCAL_ENV}
      PORT: 3000
    secrets:
      - source: aws_creds
        target: /root/.aws
    command: [  "./chamber", "exec", "basebot/local${LOCAL_ENV}", "--", "npm", "run", "start", "gistbot" ]
    ports:
      - 3002:3000
      - 9230:9229


  treasury:
    build:
      dockerfile: ./build/Dockerfile.local
      context: .
    volumes:
      - ./apps:/app/apps
      - ./libs:/app/libs
      - ./configs:/app/configs
    depends_on:
      - postgres
      - redis
      - sqs
    environment:
      NODE_OVERRIDE_ENV: local${LOCAL_ENV}
      PORT: 3000
    secrets:
      - source: aws_creds
        target: /root/.aws
    command: [  "./chamber", "exec", "basebot/local${LOCAL_ENV}", "--", "npm", "run", "start", "treasury" ]
    ports:
      - 3003:3000
      - 9233:9229


  mailbot:
    build:
      dockerfile: ../mail-bot/build/images/Dockerfile.local
      context: ../mail-bot
    volumes:
      - ../mail-bot/src:/app/src
      - ../mail-bot/configs:/app/configs
    depends_on:
      - postgres
      - redis
      - sqs
    environment:
      NODE_ENV: local
      NODE_OVERRIDE_ENV: local
      PORT: 3000
      OAUTH_REDIRECT_BASE_URL: https://gistbot-mailbot${LOCAL_ENV}.baselabs.dev/mail/oauth-public
    secrets:
      - source: aws_creds
        target: /root/.aws
    command: [  "./chamber", "exec", "mail-bot/local", "--", "npm", "run", "start:debug" ]
    ports:
      - 3004:3000
      - 9234:9229

  bull-board:
    image: probablynot/bull-board-docker:5f09cbf7e76fa6f684a4f3aeb4b23cb6fa80a7cd
    volumes:
      - ./build:/configs
    environment:
      CONFIG_FILE: /configs/bullboardConfig.json
    depends_on:
      - mailbot
      - redis
    restart: on-failure
    ports:
      - 3005:3000

# Databases
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development
    ports:
      - 5432:5432
  redis:
    image: redis:latest
    ports:
      - 6379:6379
# AWS Services
  sqs:
    image: softwaremill/elasticmq-native:latest
    logging:
      driver: none
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./build/local_sqs.conf:/opt/elasticmq.conf
