import { KnownBlock } from '@slack/web-api';
import { UserLink } from './user-link';

const generatedByAiText = `_This text was generated by our internal AI models and may contain inaccuracies._`;

export const PublicGeneratedByAIBlock = (
  requesterId: string,
  myBotUserId: string,
): KnownBlock => ({
  type: 'context',
  elements: [
    {
      type: 'mrkdwn',
      text: `This summary was requested by ${UserLink(
        requesterId,
      )}. Get your summary at: ${UserLink(myBotUserId)}.\n${generatedByAiText}`,
    },
  ],
});

export const GeneratedByAIBlock = (): KnownBlock => ({
  type: 'context',
  elements: [
    {
      type: 'mrkdwn',
      text: generatedByAiText,
    },
  ],
});
